# Generated by Django 5.2 on 2025-04-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Monthly', 'Monthly'), ('Three Months', 'Three Months'), ('Half Yearly', 'Half Yearly'), ('Yearly', 'Yearly')], default='Monthly', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fitness_classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('instructor', models.CharField(max_length=50)),
                ('plans', models.ManyToManyField(related_name='fitness_classes', to='plans.plans')),
            ],
        ),
    ]
