# Generated by Django 5.2 on 2025-04-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitness_classes',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='fitness_classes',
            name='instructor',
        ),
        migrations.AddField(
            model_name='fitness_classes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plans/images'),
        ),
    ]
