# Generated by Django 5.2 on 2025-04-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_features_alter_fitness_classes_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitness_classes',
            name='features',
            field=models.ManyToManyField(default=1, related_name='fitness_class', to='plans.features'),
        ),
    ]
