# Generated by Django 5.2 on 2025-04-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_fitness_classes_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitness_classes',
            name='features',
        ),
        migrations.DeleteModel(
            name='Features',
        ),
    ]
