# Generated by Django 5.2 on 2025-04-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('plans', '0005_remove_fitness_classes_features_delete_features'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fitness_classes',
            new_name='Fitness_classes_category',
        ),
    ]
