# Generated by Django 5.2 on 2025-04-26 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_rename_fitness_classes_fitness_classes_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduled_classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('instructor', models.CharField(max_length=50)),
                ('total_seats', models.PositiveIntegerField()),
                ('booked_seats', models.PositiveIntegerField()),
                ('fitness_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.fitness_classes_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('fitness_class', 'date_time')},
            },
        ),
    ]
