# Generated by Django 5.2 on 2025-04-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_scheduled_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduled_classes',
            name='user',
        ),
    ]
