# Generated by Django 5.2 on 2025-04-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_remove_scheduled_classes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled_classes',
            name='present_students',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
